name: HeadDrops
version: 1.5
author: pizzafreak08
main: de.dariusmewes.HeadDrops.HeadDrops
website: http://www.timolia.de/
description: Make hostile Mobs and Players drop their Heads!
commands:
    head:
        description: Gives you or someone else the head of a specific Player
        usage: /head [player] <name of head>
    headinfo:
        description: Shows the Heads name in chat upon punching it
        usage: /headinfo